<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ServerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Role
        $this->call(RoleSeeder::class);
        // User
        DB::table('users')->insert([
            // 2 Admin
            [
                'name' => 'Admin Utama',
                'email' => 'admin1@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('admin#1234'),
                'no_telp' => '081234567890',
                'role_id' => 1,
                'foto_profil' => null,
            ],
            [
                'name' => 'Admin Kedua',
                'email' => 'admin2@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('admin#5678'),
                'no_telp' => '081234567891',
                'role_id' => 1,
                'foto_profil' => null,
            ],

            // 5 Seller
            [
                'name' => 'Seller Pertama',
                'email' => 'seller1@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('seller#1234'),
                'no_telp' => '081214367890',
                'role_id' => 2,
                'foto_profil' => null,
            ],
            [
                'name' => 'Seller Kedua',
                'email' => 'seller2@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('seller#2345'),
                'no_telp' => '081224367891',
                'role_id' => 2,
                'foto_profil' => null,
            ],
            [
                'name' => 'Seller Ketiga',
                'email' => 'seller3@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('seller#3456'),
                'no_telp' => '081234467892',
                'role_id' => 2,
                'foto_profil' => null,
            ],
            [
                'name' => 'Seller Keempat',
                'email' => 'seller4@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('seller#4567'),
                'no_telp' => '081234567893',
                'role_id' => 2,
                'foto_profil' => null,
            ],
            [
                'name' => 'Seller Kelima',
                'email' => 'seller5@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('seller#5678'),
                'no_telp' => '081234567894',
                'role_id' => 2,
                'foto_profil' => null,
            ],

            // 3 Buyer
            [
                'name' => 'Buyer Pertama',
                'email' => 'buyer1@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('buyer#1234'),
                'no_telp' => '081234567895',
                'role_id' => 3,
                'foto_profil' => null,
            ],
            [
                'name' => 'Buyer Kedua',
                'email' => 'buyer2@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('buyer#2345'),
                'no_telp' => '081234567896',
                'role_id' => 3,
                'foto_profil' => null,
            ],
            [
                'name' => 'Buyer Ketiga',
                'email' => 'buyer3@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('buyer#3456'),
                'no_telp' => '081234567897',
                'role_id' => 3,
                'foto_profil' => null,
            ],
        ]);

        //Category
        DB::table('categories')->insert([
            ['nama_category' => 'Elektronik & Gadget'],
            ['nama_category' => 'Pakaian & Fashion'],
            ['nama_category' => 'Peralatan Dapur'],
            ['nama_category' => 'Mainan & Hobi'],
            ['nama_category' => 'Olahraga & Outdoor'],
            ['nama_category' => 'Kesehatan & Kecantikan'],
            ['nama_category' => 'Perabot Rumah Tangga'],
            ['nama_category' => 'Buku & Alat Tulis'],
            ['nama_category' => 'Makanan & Minuman'],
            ['nama_category' => 'Aksesoris Kendaraan'],
        ]);

        // Product
        DB::table('products')->insert([
            [
                'user_id' => 3,
                'nama_product' => 'Headphone Wireless',
                'deskripsi' => 'Headphone nirkabel berkualitas tinggi dengan bass kuat.',
                'harga' => '450000',
                'stock' => 20,
                'berat' => 500,
                'foto_cover' => 'https://t3.ftcdn.net/jpg/02/28/19/26/360_F_228192611_akMH8f6lbZ2NedZluGMgZCco0aKRKtGk.jpg',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Jaket Hoodie',
                'deskripsi' => 'Jaket hoodie nyaman untuk segala cuaca.',
                'harga' => '250000',
                'stock' => 15,
                'berat' => 700,
                'foto_cover' => 'https://www.cathayprinting.com/liteprint/application/liteprint/cathay/assets/product_image/16539997311563-hoodie.jpg',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Blender Mini',
                'deskripsi' => 'Blender mini praktis untuk smoothie harian.',
                'harga' => '320000',
                'stock' => 10,
                'berat' => 1500,
                'foto_cover' => 'https://th.bing.com/th/id/R.dfcf171fe561404aa83544402cbfffa8?rik=dldGp0V3urdAIQ&riu=http%3a%2f%2fc8.alamy.com%2fcomp%2fD93N9B%2fblender-D93N9B.jpg&ehk=jCc5VbLpRieOElBLlXP5G27UZILmKo2b1CS0Phei7Kc%3d&risl=&pid=ImgRaw&r=0',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Bola Basket',
                'deskripsi' => 'Bola basket resmi untuk latihan dan pertandingan.',
                'harga' => '180000',
                'stock' => 30,
                'berat' => 600,
                'foto_cover' => 'https://static-siplah.blibli.com/data/images/SCCS-0013-00096/02a347b8-ee71-4f01-94f8-53de88e3861f.jpeg',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Lipstik Matte',
                'deskripsi' => 'Lipstik matte tahan lama untuk tampilan sempurna.',
                'harga' => '120000',
                'stock' => 50,
                'berat' => 50,
                'foto_cover' => 'https://tse3.mm.bing.net/th/id/OIP.W3YWbbZMS28y4zdM8vLkFwHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Meja Belajar Kayu',
                'deskripsi' => 'Meja belajar kayu solid untuk kenyamanan belajar.',
                'harga' => '750000',
                'stock' => 8,
                'berat' => 15000,
                'foto_cover' => 'https://tse1.mm.bing.net/th/id/OIP.xor-2FR7-7jy2mcCLwkXVgHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Novel Thriller',
                'deskripsi' => 'Novel thriller seru dengan alur penuh misteri.',
                'harga' => '90000',
                'stock' => 40,
                'berat' => 300,
                'foto_cover' => 'https://tse4.mm.bing.net/th/id/OIP.m3Os17ZmTSpgkfIno2CfCQHaL1?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Kopi Arabika Bubuk',
                'deskripsi' => 'Kopi bubuk Arabika berkualitas premium.',
                'harga' => '85000',
                'stock' => 60,
                'berat' => 250,
                'foto_cover' => 'https://www.genpi.co/timthumb.php?src=http://fs.genpi.co/uploads/news/2018/11/24/0e33a447618d38a4991e7856b8c44bd2.jpg&w=820&h=450&a=br&zc=1',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Sarung Tangan Motor',
                'deskripsi' => 'Sarung tangan motor nyaman dan aman.',
                'harga' => '150000',
                'stock' => 25,
                'berat' => 200,
                'foto_cover' => 'https://ecs7.tokopedia.net/img/cache/700/product-1/2017/4/25/17291631/17291631_5ae552a0-1bd7-4393-9555-822c9ce68a5f_750_750.jpg',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Smartwatch',
                'deskripsi' => 'Smartwatch multifungsi untuk kegiatan sehari-hari.',
                'harga' => '950000',
                'stock' => 12,
                'berat' => 100,
                'foto_cover' => 'https://m.media-amazon.com/images/I/71rY0gIePeL.AC_SL1500.jpg',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Sepatu Sneakers',
                'deskripsi' => 'Sneakers nyaman untuk aktivitas harian.',
                'harga' => '400000',
                'stock' => 20,
                'berat' => 900,
                'foto_cover' => 'https://s.yimg.com/ny/api/res/1.2/VSRfKv1N2dcy48HO81PMXQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTk2MDtoPTcyNw--/https://media.zenfs.com/en/hearst_mens_health_171/d951aca558fbc440143428373e6fea86',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Rice Cooker',
                'deskripsi' => 'Rice cooker modern kapasitas 1.8L.',
                'harga' => '550000',
                'stock' => 15,
                'berat' => 2500,
                'foto_cover' => 'https://tse1.mm.bing.net/th/id/OIP.WU8WMZCRSqTJQ_vTXe7lvwHaHa?r=0&w=1200&h=1200&rs=1&pid=ImgDetMain&o=7&rm=3',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Masker Wajah',
                'deskripsi' => 'Masker wajah untuk perawatan kulit sehat.',
                'harga' => '50000',
                'stock' => 100,
                'berat' => 20,
                'foto_cover' => 'https://cf.shopee.co.id/file/2b704ea5fe267b87279d1b699a3bf4aa',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Kursi Kantor',
                'deskripsi' => 'Kursi kantor ergonomis dan nyaman.',
                'harga' => '1200000',
                'stock' => 5,
                'berat' => 12000,
                'foto_cover' => 'https://oscarliving.co.id/cdn/shop/files/kursi-staff-kursi-kantor-inco-casova-i-rangka-hitam-inco-shopname-255363.jpg?v=1731157966',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Buku Sketsa',
                'deskripsi' => 'Buku sketsa untuk hobi menggambar.',
                'harga' => '75000',
                'stock' => 30,
                'berat' => 200,
                'foto_cover' => 'https://id-test-11.slatic.net/p/85edb40515bdb60cec6da00855f92ad4.jpg',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Teh Herbal',
                'deskripsi' => 'Teh herbal alami untuk kesehatan.',
                'harga' => '60000',
                'stock' => 50,
                'berat' => 100,
                'foto_cover' => 'https://asset-2.tribunnews.com/health/foto/bank/images/teh-oolong.jpg',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Helm Sepeda',
                'deskripsi' => 'Helm sepeda aman dan stylish.',
                'harga' => '350000',
                'stock' => 18,
                'berat' => 800,
                'foto_cover' => 'https://contents.mediadecathlon.com/p2392082/k$40b6a599e92456e3b6dc38dc94f258fa/helm-sepeda-gunung-expl-50-hitam-rockrider-8530112.jpg',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Kamera Digital',
                'deskripsi' => 'Kamera digital dengan resolusi tinggi.',
                'harga' => '3500000',
                'stock' => 7,
                'berat' => 1200,
                'foto_cover' => 'https://asset-2.tribunnews.com/wartakota/foto/bank/images/kamera-dslr-canon-eos-250d.jpg',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Kemeja Formal',
                'deskripsi' => 'Kemeja formal cocok untuk kantor.',
                'harga' => '280000',
                'stock' => 25,
                'berat' => 400,
                'foto_cover' => 'https://cardinal.co.id/cdn/shop/files/LKI8K20P-08-1_c1f8dc10-87d5-415b-94ae-504689937e27.jpg?v=1756373093',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Microwave',
                'deskripsi' => 'Microwave cepat dan efisien.',
                'harga' => '1000000',
                'stock' => 6,
                'berat' => 10000,
                'foto_cover' => 'https://www.lg.com/content/dam/channel/wcms/id/images/microwave/ms2336gib_bbkplgn_eain_id_c/gallery/L-01.jpg',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Mainan Robot',
                'deskripsi' => 'Mainan robot interaktif untuk anak.',
                'harga' => '220000',
                'stock' => 40,
                'berat' => 300,
                'foto_cover' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR87cBVBbGtPTHIjNdwR69_IqaXoDGMcyzXf0-hfJPctQ&s&ec=73068120',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Protein Shake',
                'deskripsi' => 'Protein shake untuk kesehatan dan kebugaran.',
                'harga' => '150000',
                'stock' => 35,
                'berat' => 500,
                'foto_cover' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/opn/opn06660/y/19.jpg',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Lampu Meja LED',
                'deskripsi' => 'Lampu meja LED hemat energi.',
                'harga' => '180000',
                'stock' => 20,
                'berat' => 400,
                'foto_cover' => 'https://bela-rajastore.oss-ap-southeast-5.aliyuncs.com/prod/product/BHE3aa6s41bbZ2Z3sj6KMBrjOHgIhZoS1qVhZjON.jpg',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Tas Ransel',
                'deskripsi' => 'Tas ransel stylish dan nyaman.',
                'harga' => '350000',
                'stock' => 22,
                'berat' => 800,
                'foto_cover' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1TdLYO5t1Ri6VoZu-hkar-IS036DMToq7Qu5DlhNb6Q&s&ec=73068120',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'GPS Mobil',
                'deskripsi' => 'GPS mobil dengan fitur lengkap.',
                'harga' => '1200000',
                'stock' => 10,
                'berat' => 500,
                'foto_cover' => 'https://gpsku.co.id/wp-content/uploads/2021/06/Rekomendasi-Serta-Harga-GPS-Tracker-Mobil-Terbaik-2021.jpg',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
        ]);


        // Insert category_product
        DB::table('category_products')->insert([
            ['product_id' => 1, 'category_id' => 1],
            ['product_id' => 1, 'category_id' => 4],
            ['product_id' => 2, 'category_id' => 2],
            ['product_id' => 2, 'category_id' => 5],
            ['product_id' => 3, 'category_id' => 3],
            ['product_id' => 3, 'category_id' => 7],
            ['product_id' => 4, 'category_id' => 5],
            ['product_id' => 4, 'category_id' => 4],
            ['product_id' => 5, 'category_id' => 6],
            ['product_id' => 5, 'category_id' => 2],
            ['product_id' => 6, 'category_id' => 7],
            ['product_id' => 6, 'category_id' => 8],
            ['product_id' => 7, 'category_id' => 8],
            ['product_id' => 7, 'category_id' => 9],
            ['product_id' => 8, 'category_id' => 9],
            ['product_id' => 8, 'category_id' => 1],
            ['product_id' => 9, 'category_id' => 10],
            ['product_id' => 9, 'category_id' => 5],
            ['product_id' => 10, 'category_id' => 1],
            ['product_id' => 10, 'category_id' => 6],
            ['product_id' => 11, 'category_id' => 2],
            ['product_id' => 11, 'category_id' => 7],
            ['product_id' => 12, 'category_id' => 3],
            ['product_id' => 12, 'category_id' => 8],
            ['product_id' => 13, 'category_id' => 6],
            ['product_id' => 13, 'category_id' => 9],
            ['product_id' => 14, 'category_id' => 7],
            ['product_id' => 14, 'category_id' => 1],
            ['product_id' => 15, 'category_id' => 8],
            ['product_id' => 15, 'category_id' => 4],
            ['product_id' => 16, 'category_id' => 9],
            ['product_id' => 16, 'category_id' => 5],
            ['product_id' => 17, 'category_id' => 10],
            ['product_id' => 17, 'category_id' => 2],
            ['product_id' => 18, 'category_id' => 1],
            ['product_id' => 18, 'category_id' => 3],
            ['product_id' => 19, 'category_id' => 2],
            ['product_id' => 19, 'category_id' => 6],
            ['product_id' => 20, 'category_id' => 3],
            ['product_id' => 20, 'category_id' => 7],
            ['product_id' => 21, 'category_id' => 4],
            ['product_id' => 21, 'category_id' => 8],
            ['product_id' => 22, 'category_id' => 9],
            ['product_id' => 22, 'category_id' => 6],
            ['product_id' => 23, 'category_id' => 7],
            ['product_id' => 23, 'category_id' => 1],
            ['product_id' => 24, 'category_id' => 2],
            ['product_id' => 24, 'category_id' => 5],
            ['product_id' => 25, 'category_id' => 10],
            ['product_id' => 25, 'category_id' => 3],
        ]);

        // Alamat Toko
        DB::table('alamat_tokos')->insert([
            [
                'label' => 'BATUNUNGGAL, BANDUNG KIDUL, BANDUNG, JAWA BARAT, 40266',
                'kode_domestik' => '4866',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BANDUNG',
                'district_name' => 'BANDUNG KIDUL',
                'subdistrict_name' => 'BATUNUNGGAL',
                'zip_code' => '40266',
                'detail_alamat' => 'Jl disuatu tempat ada orang yang berjualan',
            ],
            [
                'label' => 'CAMPAKA, ANDIR, BANDUNG, JAWA BARAT, 40184',
                'kode_domestik' => '4844',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BANDUNG',
                'district_name' => 'ANDIR',
                'subdistrict_name' => 'CAMPAKA',
                'zip_code' => '40184',
                'detail_alamat' => 'Jl disuatu tempat ada orang yang berjualan',
            ],
            [
                'label' => 'CIMAHI, CIMAHI TENGAH, CIMAHI, JAWA BARAT, 40525',
                'kode_domestik' => '5256',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'CIMAHI',
                'district_name' => 'CIMAHI TENGAH',
                'subdistrict_name' => 'CIMAHI',
                'zip_code' => '40525',
                'detail_alamat' => 'Jl disuatu tempat ada orang yang berjualan',
            ],
            [
                'label' => 'DUNGUS CARIANG, ANDIR, BANDUNG, JAWA BARAT, 40183',
                'kode_domestik' => '4846',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BANDUNG',
                'district_name' => 'ANDIR',
                'subdistrict_name' => 'DUNGUS CARIANG',
                'zip_code' => '40183',
                'detail_alamat' => 'Jl disuatu tempat ada orang yang berjualan',
            ],
            [
                'label' => 'WARUNG MUNCANG, BANDUNG KULON, BANDUNG, JAWA BARAT, 40211',
                'kode_domestik' => '4877',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BANDUNG',
                'district_name' => 'BANDUNG KULON',
                'subdistrict_name' => 'WARUNG MUNCANG',
                'zip_code' => '40211',
                'detail_alamat' => 'Jl disuatu tempat ada orang yang berjualan',
            ],
        ]);

        // Toko
        DB::table('tokos')->insert([
            [
                'user_id' => 3,
                'nama_toko' => 'Toko Elektronik ABC',
                'deskripsi' => 'Menjual berbagai produk elektronik berkualitas.',
                'no_telp' => '081234567890',
                'alamat_toko_id' => 1,
            ],
            [
                'user_id' => 4,
                'nama_toko' => 'Fashionista Store',
                'deskripsi' => 'Pakaian dan aksesoris fashion terbaru.',
                'no_telp' => '082134567891',
                'alamat_toko_id' => 2,
            ],
            [
                'user_id' => 5,
                'nama_toko' => 'Dapur Sehat',
                'deskripsi' => 'Peralatan dapur modern untuk kebutuhan Anda.',
                'no_telp' => '083134567892',
                'alamat_toko_id' => 3,
            ],
            [
                'user_id' => 6,
                'nama_toko' => 'Hobi & Olahraga',
                'deskripsi' => 'Mainan, alat olahraga, dan perlengkapan hobi.',
                'no_telp' => '084134567893',
                'alamat_toko_id' => 4,
            ],
            [
                'user_id' => 7,
                'nama_toko' => 'Kecantikan & Kesehatan',
                'deskripsi' => 'Produk kecantikan dan kesehatan terbaik.',
                'no_telp' => '085134567894',
                'alamat_toko_id' => 5,
            ],
        ]);

        // Alamat Pengguna
        DB::table('alamat_users')->insert([
            [
                'user_id' => 1,
                'nama_penerima' => 'Admin Utama',
                'kode_domestik' => '8427',
                'label' => 'DAGO, PARUNG PANJANG, BOGOR, JAWA BARAT, 16360',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BOGOR',
                'district_name' => 'PARUNG PANJANG',
                'subdistrict_name' => 'DAGO',
                'zip_code' => '16360',
                'detail_alamat' => 'Jl. Raya Dago No. 12, dekat Pasar Parung Panjang',
            ],
            [
                'user_id' => 2,
                'nama_penerima' => 'Admin Kedua',
                'kode_domestik' => '8427',
                'label' => 'DAGO, PARUNG PANJANG, BOGOR, JAWA BARAT, 16360',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BOGOR',
                'district_name' => 'PARUNG PANJANG',
                'subdistrict_name' => 'DAGO',
                'zip_code' => '16360',
                'detail_alamat' => 'Perumahan Griya Asri Blok B2 No. 7',
            ],
            [
                'user_id' => 8,
                'nama_penerima' => 'Andi Susanto',
                'kode_domestik' => '4866',
                'label' => 'BATUNUNGGAL, BANDUNG KIDUL, BANDUNG, JAWA BARAT, 40266',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BANDUNG',
                'district_name' => 'BANDUNG KIDUL',
                'subdistrict_name' => 'BATUNUNGGAL',
                'zip_code' => '40266',
                'detail_alamat' => 'Jl. Batununggal Indah I No. 23 RT 04 RW 05',
            ],
            [
                'user_id' => 9,
                'nama_penerima' => 'Siti Aminah',
                'kode_domestik' => '4844',
                'label' => 'CAMPAKA, ANDIR, BANDUNG, JAWA BARAT, 40184',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BANDUNG',
                'district_name' => 'ANDIR',
                'subdistrict_name' => 'CAMPAKA',
                'zip_code' => '40184',
                'detail_alamat' => 'Komplek Permata Andir No. 45',
            ],
            [
                'user_id' => 10,
                'nama_penerima' => 'Budi Hartono',
                'kode_domestik' => '5256',
                'label' => 'CIMAHI, CIMAHI TENGAH, CIMAHI, JAWA BARAT, 40525',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'CIMAHI',
                'district_name' => 'CIMAHI TENGAH',
                'subdistrict_name' => 'CIMAHI',
                'zip_code' => '40525',
                'detail_alamat' => 'Jl. Sangkuriang Tengah No. 89, dekat Masjid Al-Hikmah',
            ],
        ]);
    }
}
