<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ServerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Role
        $this->call(RoleSeeder::class);
        // User
        DB::table('users')->insert([
            // 2 Admin
            [
                'name' => 'Admin Utama',
                'email' => 'admin1@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('admin#1234'),
                'no_telp' => '081234567890',
                'role_id' => 1,
                'foto_profil' => null,
            ],
            [
                'name' => 'Admin Kedua',
                'email' => 'admin2@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('admin#5678'),
                'no_telp' => '081234567891',
                'role_id' => 1,
                'foto_profil' => null,
            ],

            // 5 Seller
            [
                'name' => 'Seller Pertama',
                'email' => 'seller1@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('seller#1234'),
                'no_telp' => '081214367890',
                'role_id' => 2,
                'foto_profil' => null,
            ],
            [
                'name' => 'Seller Kedua',
                'email' => 'seller2@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('seller#2345'),
                'no_telp' => '081224367891',
                'role_id' => 2,
                'foto_profil' => null,
            ],
            [
                'name' => 'Seller Ketiga',
                'email' => 'seller3@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('seller#3456'),
                'no_telp' => '081234467892',
                'role_id' => 2,
                'foto_profil' => null,
            ],
            [
                'name' => 'Seller Keempat',
                'email' => 'seller4@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('seller#4567'),
                'no_telp' => '081234567893',
                'role_id' => 2,
                'foto_profil' => null,
            ],
            [
                'name' => 'Seller Kelima',
                'email' => 'seller5@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('seller#5678'),
                'no_telp' => '081234567894',
                'role_id' => 2,
                'foto_profil' => null,
            ],

            // 3 Buyer
            [
                'name' => 'Buyer Pertama',
                'email' => 'buyer1@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('buyer#1234'),
                'no_telp' => '081234567895',
                'role_id' => 3,
                'foto_profil' => null,
            ],
            [
                'name' => 'Buyer Kedua',
                'email' => 'buyer2@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('buyer#2345'),
                'no_telp' => '081234567896',
                'role_id' => 3,
                'foto_profil' => null,
            ],
            [
                'name' => 'Buyer Ketiga',
                'email' => 'buyer3@shop.com',
                'email_verified_at' => now(),
                'password' => Hash::make('buyer#3456'),
                'no_telp' => '081234567897',
                'role_id' => 3,
                'foto_profil' => null,
            ],
        ]);

        //Category
        DB::table('categories')->insert([
            ['nama_category' => 'Elektronik & Gadget'],
            ['nama_category' => 'Pakaian & Fashion'],
            ['nama_category' => 'Peralatan Dapur'],
            ['nama_category' => 'Mainan & Hobi'],
            ['nama_category' => 'Olahraga & Outdoor'],
            ['nama_category' => 'Kesehatan & Kecantikan'],
            ['nama_category' => 'Perabot Rumah Tangga'],
            ['nama_category' => 'Buku & Alat Tulis'],
            ['nama_category' => 'Makanan & Minuman'],
            ['nama_category' => 'Aksesoris Kendaraan'],
        ]);

        // Product
        DB::table('products')->insert([
            [
                'user_id' => 3,
                'nama_product' => 'Smartphone Android',
                'deskripsi' => 'Smartphone canggih dengan layar AMOLED dan RAM 8GB.',
                'harga' => '3500000',
                'stock' => 50,
                'berat' => 400,
                'foto_cover' => 'https://loremflickr.com/500/500/smartphone',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Laptop Gaming',
                'deskripsi' => 'Laptop gaming dengan GPU RTX 3060 dan layar 144Hz.',
                'harga' => '15000000',
                'stock' => 10,
                'berat' => 2500,
                'foto_cover' => 'https://loremflickr.com/500/500/gaming,laptop',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Headphone Noise Cancelling',
                'deskripsi' => 'Headphone bluetooth dengan fitur active noise cancelling.',
                'harga' => '1200000',
                'stock' => 30,
                'berat' => 500,
                'foto_cover' => 'https://loremflickr.com/500/500/headphone',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Smart TV 43 Inch',
                'deskripsi' => 'Smart TV Android resolusi 4K dengan bezel tipis.',
                'harga' => '4500000',
                'stock' => 15,
                'berat' => 8000,
                'foto_cover' => 'https://loremflickr.com/500/500/television',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Powerbank 20000mAh',
                'deskripsi' => 'Powerbank fast charging 20W kapasitas besar.',
                'harga' => '250000',
                'stock' => 100,
                'berat' => 400,
                'foto_cover' => 'https://loremflickr.com/500/500/powerbank',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Kamera Mirrorless',
                'deskripsi' => 'Kamera mirrorless 24MP dengan lensa kit 15-45mm.',
                'harga' => '8500000',
                'stock' => 5,
                'berat' => 800,
                'foto_cover' => 'https://loremflickr.com/500/500/mirrorless,camera',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Mouse Wireless',
                'deskripsi' => 'Mouse nirkabel ergonomis dengan sensor optik presisi.',
                'harga' => '150000',
                'stock' => 80,
                'berat' => 150,
                'foto_cover' => 'https://loremflickr.com/500/500/wireless,mouse',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Keyboard Mekanikal',
                'deskripsi' => 'Keyboard mekanikal switch biru dengan lampu RGB.',
                'harga' => '450000',
                'stock' => 40,
                'berat' => 900,
                'foto_cover' => 'https://loremflickr.com/500/500/mechanical,keyboard',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Kipas Angin Berdiri',
                'deskripsi' => 'Kipas angin dengan 3 mode kecepatan dan remote.',
                'harga' => '350000',
                'stock' => 20,
                'berat' => 4000,
                'foto_cover' => 'https://loremflickr.com/500/500/standing,fan',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'AC Split 1 PK',
                'deskripsi' => 'AC hemat energi dengan fitur pendingin cepat.',
                'harga' => '3200000',
                'stock' => 8,
                'berat' => 25000,
                'foto_cover' => 'https://loremflickr.com/500/500/air,conditioner',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Speaker Bluetooth Portable',
                'deskripsi' => 'Speaker bass mantap tahan air IPX7.',
                'harga' => '550000',
                'stock' => 50,
                'berat' => 600,
                'foto_cover' => 'https://loremflickr.com/500/500/bluetooth,speaker',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'TWS Earbuds',
                'deskripsi' => 'Earbuds nirkabel dengan baterai tahan 24 jam.',
                'harga' => '350000',
                'stock' => 60,
                'berat' => 100,
                'foto_cover' => 'https://loremflickr.com/500/500/earbuds',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Flashdisk 64GB',
                'deskripsi' => 'Flashdisk USB 3.0 transfer rate tinggi.',
                'harga' => '85000',
                'stock' => 150,
                'berat' => 50,
                'foto_cover' => 'https://loremflickr.com/500/500/flashdrive',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'SSD Eksternal 1TB',
                'deskripsi' => 'Penyimpanan portabel super cepat untuk backup.',
                'harga' => '1250000',
                'stock' => 25,
                'berat' => 150,
                'foto_cover' => 'https://loremflickr.com/500/500/external,ssd',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 3,
                'nama_product' => 'Proyektor Mini',
                'deskripsi' => 'Proyektor portabel untuk hiburan di rumah.',
                'harga' => '850000',
                'stock' => 15,
                'berat' => 1200,
                'foto_cover' => 'https://loremflickr.com/500/500/mini,projector',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Kemeja Flanel Pria',
                'deskripsi' => 'Kemeja flanel lengan panjang motif kotak elegan.',
                'harga' => '150000',
                'stock' => 50,
                'berat' => 300,
                'foto_cover' => 'https://loremflickr.com/500/500/shirt,men',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Kaos Polos Cotton Combed',
                'deskripsi' => 'Kaos bahan katun 30s adem dan menyerap keringat.',
                'harga' => '45000',
                'stock' => 200,
                'berat' => 150,
                'foto_cover' => 'https://loremflickr.com/500/500/tshirt,blank',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Celana Jeans Denim',
                'deskripsi' => 'Celana jeans slim fit pria bahan stretch.',
                'harga' => '250000',
                'stock' => 40,
                'berat' => 600,
                'foto_cover' => 'https://loremflickr.com/500/500/jeans',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Jaket Hoodie Oversize',
                'deskripsi' => 'Jaket hoodie kasual untuk pria dan wanita.',
                'harga' => '175000',
                'stock' => 30,
                'berat' => 700,
                'foto_cover' => 'https://loremflickr.com/500/500/hoodie',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Sepatu Sneakers Putih',
                'deskripsi' => 'Sepatu kasual ringan dan nyaman dipakai harian.',
                'harga' => '350000',
                'stock' => 25,
                'berat' => 800,
                'foto_cover' => 'https://loremflickr.com/500/500/sneakers',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Topi Baseball',
                'deskripsi' => 'Topi bordir simpel cocok untuk outdoor.',
                'harga' => '65000',
                'stock' => 100,
                'berat' => 100,
                'foto_cover' => 'https://loremflickr.com/500/500/baseball,cap',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Kacamata Hitam Polarized',
                'deskripsi' => 'Kacamata anti UV untuk aktivitas luar ruangan.',
                'harga' => '125000',
                'stock' => 60,
                'berat' => 150,
                'foto_cover' => 'https://loremflickr.com/500/500/sunglasses',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Jam Tangan Pria Kulit',
                'deskripsi' => 'Jam tangan analog klasik dengan strap kulit.',
                'harga' => '450000',
                'stock' => 20,
                'berat' => 200,
                'foto_cover' => 'https://loremflickr.com/500/500/watch,men',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Tas Selempang Kanvas',
                'deskripsi' => 'Tas selempang multifungsi banyak kompartemen.',
                'harga' => '180000',
                'stock' => 40,
                'berat' => 450,
                'foto_cover' => 'https://loremflickr.com/500/500/slingbag',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Dompet Kulit Asli',
                'deskripsi' => 'Dompet pria desain lipat bahan kulit premium.',
                'harga' => '220000',
                'stock' => 35,
                'berat' => 150,
                'foto_cover' => 'https://loremflickr.com/500/500/leather,wallet',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Blouse Kerja Wanita',
                'deskripsi' => 'Blouse elegan untuk pakaian kantor wanita.',
                'harga' => '160000',
                'stock' => 45,
                'berat' => 250,
                'foto_cover' => 'https://loremflickr.com/500/500/blouse',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Rok Plisket Panjang',
                'deskripsi' => 'Rok lipit wanita bahan tebal dan jatuh.',
                'harga' => '110000',
                'stock' => 50,
                'berat' => 350,
                'foto_cover' => 'https://loremflickr.com/500/500/skirt',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Hijab Pashmina Ceruty',
                'deskripsi' => 'Hijab panjang mudah dibentuk berbagai gaya.',
                'harga' => '45000',
                'stock' => 150,
                'berat' => 100,
                'foto_cover' => 'https://loremflickr.com/500/500/hijab',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Sepatu Heels 5cm',
                'deskripsi' => 'Sepatu hak tinggi desain modern untuk pesta.',
                'harga' => '280000',
                'stock' => 20,
                'berat' => 650,
                'foto_cover' => 'https://loremflickr.com/500/500/heels',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 4,
                'nama_product' => 'Handbag Wanita',
                'deskripsi' => 'Tas tangan kulit sintetis elegan dengan tali panjang.',
                'harga' => '240000',
                'stock' => 25,
                'berat' => 750,
                'foto_cover' => 'https://loremflickr.com/500/500/handbag',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Set Panci Stainless',
                'deskripsi' => 'Set panci masak 5 in 1 bahan stainless anti karat.',
                'harga' => '450000',
                'stock' => 15,
                'berat' => 3500,
                'foto_cover' => 'https://loremflickr.com/500/500/pan,set',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Wajan Anti Lengket 28cm',
                'deskripsi' => 'Teflon wajan tebal mudah dibersihkan.',
                'harga' => '185000',
                'stock' => 30,
                'berat' => 1200,
                'foto_cover' => 'https://loremflickr.com/500/500/frying,pan',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Set Pisau Dapur',
                'deskripsi' => 'Pisau tajam 6 pcs lengkap dengan talenan.',
                'harga' => '125000',
                'stock' => 40,
                'berat' => 800,
                'foto_cover' => 'https://loremflickr.com/500/500/kitchen,knife',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Talenan Kayu Jati',
                'deskripsi' => 'Talenan kokoh dan tahan lama dari kayu jati.',
                'harga' => '85000',
                'stock' => 50,
                'berat' => 1000,
                'foto_cover' => 'https://loremflickr.com/500/500/cutting,board',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Blender Kaca 2L',
                'deskripsi' => 'Blender kuat penghancur es dan buah.',
                'harga' => '350000',
                'stock' => 20,
                'berat' => 2500,
                'foto_cover' => 'https://loremflickr.com/500/500/blender',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Mixer Tangan',
                'deskripsi' => 'Hand mixer untuk adonan kue 5 kecepatan.',
                'harga' => '250000',
                'stock' => 25,
                'berat' => 1500,
                'foto_cover' => 'https://loremflickr.com/500/500/mixer',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Rice Cooker Digital',
                'deskripsi' => 'Penanak nasi pintar dengan banyak mode masak.',
                'harga' => '550000',
                'stock' => 15,
                'berat' => 3000,
                'foto_cover' => 'https://loremflickr.com/500/500/rice,cooker',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Oven Listrik 19L',
                'deskripsi' => 'Oven low watt cocok untuk baking rumahan.',
                'harga' => '750000',
                'stock' => 10,
                'berat' => 5500,
                'foto_cover' => 'https://loremflickr.com/500/500/oven',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Spatula Silikon Set',
                'deskripsi' => 'Spatula tahan panas 11 pcs food grade.',
                'harga' => '150000',
                'stock' => 40,
                'berat' => 600,
                'foto_cover' => 'https://loremflickr.com/500/500/spatula',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Timbangan Dapur Digital',
                'deskripsi' => 'Timbangan kue akurasi 1 gram.',
                'harga' => '65000',
                'stock' => 60,
                'berat' => 350,
                'foto_cover' => 'https://loremflickr.com/500/500/kitchen,scale',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Gelas Kaca Set 6 Pcs',
                'deskripsi' => 'Set gelas minum tebal desain minimalis.',
                'harga' => '95000',
                'stock' => 35,
                'berat' => 1800,
                'foto_cover' => 'https://loremflickr.com/500/500/glass,set',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Piring Keramik Aesthetic',
                'deskripsi' => 'Piring makan cantik untuk hidangan spesial.',
                'harga' => '45000',
                'stock' => 80,
                'berat' => 400,
                'foto_cover' => 'https://loremflickr.com/500/500/ceramic,plate',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Rak Piring Minimalis',
                'deskripsi' => 'Rak pengering piring anti karat.',
                'harga' => '220000',
                'stock' => 20,
                'berat' => 2000,
                'foto_cover' => 'https://loremflickr.com/500/500/dish,rack',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Set Tempat Bumbu',
                'deskripsi' => 'Wadah bumbu kaca kedap udara dengan rak kayu.',
                'harga' => '135000',
                'stock' => 30,
                'berat' => 1100,
                'foto_cover' => 'https://loremflickr.com/500/500/spice,jar',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 5,
                'nama_product' => 'Teko Listrik Pemanas Air',
                'deskripsi' => 'Kettle elektrik stainless cepat mendidih.',
                'harga' => '160000',
                'stock' => 40,
                'berat' => 1200,
                'foto_cover' => 'https://loremflickr.com/500/500/kettle',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Bola Sepak Original',
                'deskripsi' => 'Bola sepak standar FIFA bahan PU.',
                'harga' => '250000',
                'stock' => 30,
                'berat' => 500,
                'foto_cover' => 'https://loremflickr.com/500/500/soccer,ball',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Raket Badminton Pro',
                'deskripsi' => 'Raket ringan tarikan tinggi untuk turnamen.',
                'harga' => '450000',
                'stock' => 25,
                'berat' => 400,
                'foto_cover' => 'https://loremflickr.com/500/500/badminton,racket',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Sepatu Lari Running',
                'deskripsi' => 'Sepatu olahraga pria ringan empuk bernapas.',
                'harga' => '550000',
                'stock' => 20,
                'berat' => 850,
                'foto_cover' => 'https://loremflickr.com/500/500/running,shoes',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Matras Yoga Anti Slip',
                'deskripsi' => 'Matras senam ketebalan 8mm.',
                'harga' => '120000',
                'stock' => 45,
                'berat' => 1200,
                'foto_cover' => 'https://loremflickr.com/500/500/yoga,mat',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Dumbbell Barbel 5kg',
                'deskripsi' => 'Beban angkat besi lapis karet 5kg.',
                'harga' => '150000',
                'stock' => 50,
                'berat' => 5000,
                'foto_cover' => 'https://loremflickr.com/500/500/dumbbell',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Tenda Camping 4 Orang',
                'deskripsi' => 'Tenda dome double layer anti air hujan.',
                'harga' => '650000',
                'stock' => 15,
                'berat' => 3500,
                'foto_cover' => 'https://loremflickr.com/500/500/camping,tent',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Sleeping Bag',
                'deskripsi' => 'Kantung tidur hangat untuk naik gunung.',
                'harga' => '180000',
                'stock' => 35,
                'berat' => 1000,
                'foto_cover' => 'https://loremflickr.com/500/500/sleeping,bag',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Sepeda Lipat 20 Inch',
                'deskripsi' => 'Sepeda praktis rangka alloy ringan.',
                'harga' => '2500000',
                'stock' => 5,
                'berat' => 15000,
                'foto_cover' => 'https://loremflickr.com/500/500/folding,bike',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Helm Sepeda MTB',
                'deskripsi' => 'Helm gowes aman dengan ventilasi udara baik.',
                'harga' => '220000',
                'stock' => 30,
                'berat' => 600,
                'foto_cover' => 'https://loremflickr.com/500/500/bicycle,helmet',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Action Figure Anime',
                'deskripsi' => 'Figur koleksi detail tinggi tinggi 20cm.',
                'harga' => '350000',
                'stock' => 20,
                'berat' => 450,
                'foto_cover' => 'https://loremflickr.com/500/500/action,figure',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Lego Brick Set',
                'deskripsi' => 'Mainan susun blok edukasi anak isi 500 pcs.',
                'harga' => '450000',
                'stock' => 15,
                'berat' => 800,
                'foto_cover' => 'https://loremflickr.com/500/500/lego',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Puzzle 1000 Pcs',
                'deskripsi' => 'Puzzle gambar pemandangan mengasah otak.',
                'harga' => '125000',
                'stock' => 25,
                'berat' => 700,
                'foto_cover' => 'https://loremflickr.com/500/500/puzzle',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Drone Kamera 4K',
                'deskripsi' => 'Drone quadcopter dengan kamera HD dan stabilisasi.',
                'harga' => '1200000',
                'stock' => 10,
                'berat' => 1500,
                'foto_cover' => 'https://loremflickr.com/500/500/drone',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Skateboard Maple',
                'deskripsi' => 'Papan luncur profesional bahan kayu maple asli.',
                'harga' => '480000',
                'stock' => 15,
                'berat' => 2500,
                'foto_cover' => 'https://loremflickr.com/500/500/skateboard',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 6,
                'nama_product' => 'Gitar Akustik Pemula',
                'deskripsi' => 'Gitar akustik dengan senar string empuk.',
                'harga' => '550000',
                'stock' => 10,
                'berat' => 3000,
                'foto_cover' => 'https://loremflickr.com/500/500/acoustic,guitar',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Lipstik Matte Tahan Lama',
                'deskripsi' => 'Lip cream warna natural tidak membuat bibir kering.',
                'harga' => '85000',
                'stock' => 100,
                'berat' => 50,
                'foto_cover' => 'https://loremflickr.com/500/500/lipstick',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Foundation Liquid Coverage',
                'deskripsi' => 'Alas bedak cair menutupi noda dengan sempurna.',
                'harga' => '145000',
                'stock' => 60,
                'berat' => 150,
                'foto_cover' => 'https://loremflickr.com/500/500/foundation,makeup',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Maskara Waterproof',
                'deskripsi' => 'Pelentik bulu mata anti air tahan 24 jam.',
                'harga' => '95000',
                'stock' => 80,
                'berat' => 80,
                'foto_cover' => 'https://loremflickr.com/500/500/mascara',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Eyeshadow Palette',
                'deskripsi' => 'Palet perona mata 12 warna pigmen tinggi.',
                'harga' => '175000',
                'stock' => 40,
                'berat' => 200,
                'foto_cover' => 'https://loremflickr.com/500/500/eyeshadow',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Skincare Glowing Set',
                'deskripsi' => 'Paket perawatan wajah mencerahkan siang malam.',
                'harga' => '350000',
                'stock' => 30,
                'berat' => 500,
                'foto_cover' => 'https://loremflickr.com/500/500/skincare',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Serum Wajah Anti Aging',
                'deskripsi' => 'Serum mengandung retinol untuk mencegah penuaan.',
                'harga' => '155000',
                'stock' => 50,
                'berat' => 120,
                'foto_cover' => 'https://loremflickr.com/500/500/face,serum',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Sunscreen SPF 50',
                'deskripsi' => 'Tabir surya ringan tanpa whitecast perlindungan UV.',
                'harga' => '80000',
                'stock' => 120,
                'berat' => 100,
                'foto_cover' => 'https://loremflickr.com/500/500/sunscreen',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Sabun Mandi Cair 1L',
                'deskripsi' => 'Body wash melembabkan dengan aroma bunga.',
                'harga' => '65000',
                'stock' => 70,
                'berat' => 1100,
                'foto_cover' => 'https://loremflickr.com/500/500/body,wash',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Shampo Anti Ketombe',
                'deskripsi' => 'Sampo perawatan kulit kepala membersihkan ketombe.',
                'harga' => '55000',
                'stock' => 80,
                'berat' => 600,
                'foto_cover' => 'https://loremflickr.com/500/500/shampoo',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Parfum Wanita Elegan',
                'deskripsi' => 'Minyak wangi tahan lama aroma manis floral.',
                'harga' => '250000',
                'stock' => 45,
                'berat' => 300,
                'foto_cover' => 'https://loremflickr.com/500/500/perfume',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Vitamin C 1000mg',
                'deskripsi' => 'Suplemen daya tahan tubuh isi 30 tablet.',
                'harga' => '75000',
                'stock' => 150,
                'berat' => 200,
                'foto_cover' => 'https://loremflickr.com/500/500/vitamin,c',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Masker Medis 3 Ply',
                'deskripsi' => 'Masker pelindung sekali pakai isi 50 pcs.',
                'harga' => '35000',
                'stock' => 200,
                'berat' => 300,
                'foto_cover' => 'https://loremflickr.com/500/500/medical,mask',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Hand Sanitizer Gel',
                'deskripsi' => 'Pembersih tangan tanpa bilas antiseptik wangi.',
                'harga' => '25000',
                'stock' => 100,
                'berat' => 250,
                'foto_cover' => 'https://loremflickr.com/500/500/hand,sanitizer',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Thermometer Gun Digital',
                'deskripsi' => 'Alat pengukur suhu tubuh inframerah tanpa kontak.',
                'harga' => '125000',
                'stock' => 40,
                'berat' => 250,
                'foto_cover' => 'https://loremflickr.com/500/500/thermometer',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
            [
                'user_id' => 7,
                'nama_product' => 'Alat Pijat Wajah Roller',
                'deskripsi' => 'Face roller jade untuk relaksasi otot wajah.',
                'harga' => '45000',
                'stock' => 60,
                'berat' => 150,
                'foto_cover' => 'https://loremflickr.com/500/500/face,roller',
                'terjual' => 0,
                'status_produk' => 'publish',
            ],
        ]);

        // Insert category_product
        DB::table('category_products')->insert([
            [
                'product_id' => 1,
                'category_id' => 1,
            ],
            [
                'product_id' => 2,
                'category_id' => 1,
            ],
            [
                'product_id' => 3,
                'category_id' => 1,
            ],
            [
                'product_id' => 4,
                'category_id' => 1,
            ],
            [
                'product_id' => 4,
                'category_id' => 7,
            ],
            [
                'product_id' => 5,
                'category_id' => 1,
            ],
            [
                'product_id' => 6,
                'category_id' => 1,
            ],
            [
                'product_id' => 7,
                'category_id' => 1,
            ],
            [
                'product_id' => 8,
                'category_id' => 1,
            ],
            [
                'product_id' => 9,
                'category_id' => 1,
            ],
            [
                'product_id' => 9,
                'category_id' => 7,
            ],
            [
                'product_id' => 10,
                'category_id' => 1,
            ],
            [
                'product_id' => 10,
                'category_id' => 7,
            ],
            [
                'product_id' => 11,
                'category_id' => 1,
            ],
            [
                'product_id' => 12,
                'category_id' => 1,
            ],
            [
                'product_id' => 13,
                'category_id' => 1,
            ],
            [
                'product_id' => 14,
                'category_id' => 1,
            ],
            [
                'product_id' => 15,
                'category_id' => 1,
            ],
            [
                'product_id' => 16,
                'category_id' => 2,
            ],
            [
                'product_id' => 17,
                'category_id' => 2,
            ],
            [
                'product_id' => 18,
                'category_id' => 2,
            ],
            [
                'product_id' => 19,
                'category_id' => 2,
            ],
            [
                'product_id' => 20,
                'category_id' => 2,
            ],
            [
                'product_id' => 21,
                'category_id' => 2,
            ],
            [
                'product_id' => 21,
                'category_id' => 5,
            ],
            [
                'product_id' => 22,
                'category_id' => 2,
            ],
            [
                'product_id' => 23,
                'category_id' => 2,
            ],
            [
                'product_id' => 24,
                'category_id' => 2,
            ],
            [
                'product_id' => 25,
                'category_id' => 2,
            ],
            [
                'product_id' => 26,
                'category_id' => 2,
            ],
            [
                'product_id' => 27,
                'category_id' => 2,
            ],
            [
                'product_id' => 28,
                'category_id' => 2,
            ],
            [
                'product_id' => 29,
                'category_id' => 2,
            ],
            [
                'product_id' => 30,
                'category_id' => 2,
            ],
            [
                'product_id' => 31,
                'category_id' => 3,
            ],
            [
                'product_id' => 31,
                'category_id' => 7,
            ],
            [
                'product_id' => 32,
                'category_id' => 3,
            ],
            [
                'product_id' => 33,
                'category_id' => 3,
            ],
            [
                'product_id' => 34,
                'category_id' => 3,
            ],
            [
                'product_id' => 35,
                'category_id' => 3,
            ],
            [
                'product_id' => 35,
                'category_id' => 1,
            ],
            [
                'product_id' => 36,
                'category_id' => 3,
            ],
            [
                'product_id' => 36,
                'category_id' => 1,
            ],
            [
                'product_id' => 37,
                'category_id' => 3,
            ],
            [
                'product_id' => 37,
                'category_id' => 1,
            ],
            [
                'product_id' => 38,
                'category_id' => 3,
            ],
            [
                'product_id' => 38,
                'category_id' => 1,
            ],
            [
                'product_id' => 39,
                'category_id' => 3,
            ],
            [
                'product_id' => 40,
                'category_id' => 3,
            ],
            [
                'product_id' => 41,
                'category_id' => 3,
            ],
            [
                'product_id' => 41,
                'category_id' => 7,
            ],
            [
                'product_id' => 42,
                'category_id' => 3,
            ],
            [
                'product_id' => 42,
                'category_id' => 7,
            ],
            [
                'product_id' => 43,
                'category_id' => 3,
            ],
            [
                'product_id' => 43,
                'category_id' => 7,
            ],
            [
                'product_id' => 44,
                'category_id' => 3,
            ],
            [
                'product_id' => 45,
                'category_id' => 3,
            ],
            [
                'product_id' => 45,
                'category_id' => 1,
            ],
            [
                'product_id' => 46,
                'category_id' => 5,
            ],
            [
                'product_id' => 47,
                'category_id' => 5,
            ],
            [
                'product_id' => 48,
                'category_id' => 5,
            ],
            [
                'product_id' => 48,
                'category_id' => 2,
            ],
            [
                'product_id' => 49,
                'category_id' => 5,
            ],
            [
                'product_id' => 50,
                'category_id' => 5,
            ],
            [
                'product_id' => 51,
                'category_id' => 5,
            ],
            [
                'product_id' => 52,
                'category_id' => 5,
            ],
            [
                'product_id' => 53,
                'category_id' => 5,
            ],
            [
                'product_id' => 54,
                'category_id' => 5,
            ],
            [
                'product_id' => 55,
                'category_id' => 4,
            ],
            [
                'product_id' => 56,
                'category_id' => 4,
            ],
            [
                'product_id' => 57,
                'category_id' => 4,
            ],
            [
                'product_id' => 58,
                'category_id' => 4,
            ],
            [
                'product_id' => 58,
                'category_id' => 1,
            ],
            [
                'product_id' => 59,
                'category_id' => 5,
            ],
            [
                'product_id' => 59,
                'category_id' => 4,
            ],
            [
                'product_id' => 60,
                'category_id' => 4,
            ],
            [
                'product_id' => 61,
                'category_id' => 6,
            ],
            [
                'product_id' => 62,
                'category_id' => 6,
            ],
            [
                'product_id' => 63,
                'category_id' => 6,
            ],
            [
                'product_id' => 64,
                'category_id' => 6,
            ],
            [
                'product_id' => 65,
                'category_id' => 6,
            ],
            [
                'product_id' => 66,
                'category_id' => 6,
            ],
            [
                'product_id' => 67,
                'category_id' => 6,
            ],
            [
                'product_id' => 68,
                'category_id' => 6,
            ],
            [
                'product_id' => 69,
                'category_id' => 6,
            ],
            [
                'product_id' => 70,
                'category_id' => 6,
            ],
            [
                'product_id' => 71,
                'category_id' => 6,
            ],
            [
                'product_id' => 71,
                'category_id' => 9,
            ],
            [
                'product_id' => 72,
                'category_id' => 6,
            ],
            [
                'product_id' => 73,
                'category_id' => 6,
            ],
            [
                'product_id' => 74,
                'category_id' => 6,
            ],
            [
                'product_id' => 74,
                'category_id' => 1,
            ],
            [
                'product_id' => 75,
                'category_id' => 6,
            ],
        ]);

        // Alamat Toko
        DB::table('alamat_tokos')->insert([
            [
                'label' => 'BATUNUNGGAL, BANDUNG KIDUL, BANDUNG, JAWA BARAT, 40266',
                'kode_domestik' => '4866',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BANDUNG',
                'district_name' => 'BANDUNG KIDUL',
                'subdistrict_name' => 'BATUNUNGGAL',
                'zip_code' => '40266',
                'detail_alamat' => 'Jl disuatu tempat ada orang yang berjualan',
            ],
            [
                'label' => 'CAMPAKA, ANDIR, BANDUNG, JAWA BARAT, 40184',
                'kode_domestik' => '4844',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BANDUNG',
                'district_name' => 'ANDIR',
                'subdistrict_name' => 'CAMPAKA',
                'zip_code' => '40184',
                'detail_alamat' => 'Jl disuatu tempat ada orang yang berjualan',
            ],
            [
                'label' => 'CIMAHI, CIMAHI TENGAH, CIMAHI, JAWA BARAT, 40525',
                'kode_domestik' => '5256',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'CIMAHI',
                'district_name' => 'CIMAHI TENGAH',
                'subdistrict_name' => 'CIMAHI',
                'zip_code' => '40525',
                'detail_alamat' => 'Jl disuatu tempat ada orang yang berjualan',
            ],
            [
                'label' => 'DUNGUS CARIANG, ANDIR, BANDUNG, JAWA BARAT, 40183',
                'kode_domestik' => '4846',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BANDUNG',
                'district_name' => 'ANDIR',
                'subdistrict_name' => 'DUNGUS CARIANG',
                'zip_code' => '40183',
                'detail_alamat' => 'Jl disuatu tempat ada orang yang berjualan',
            ],
            [
                'label' => 'WARUNG MUNCANG, BANDUNG KULON, BANDUNG, JAWA BARAT, 40211',
                'kode_domestik' => '4877',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BANDUNG',
                'district_name' => 'BANDUNG KULON',
                'subdistrict_name' => 'WARUNG MUNCANG',
                'zip_code' => '40211',
                'detail_alamat' => 'Jl disuatu tempat ada orang yang berjualan',
            ],
        ]);

        // Toko
        DB::table('tokos')->insert([
            [
                'user_id' => 3,
                'nama_toko' => 'Toko Elektronik ABC',
                'deskripsi' => 'Menjual berbagai produk elektronik berkualitas.',
                'no_telp' => '081234567890',
                'alamat_toko_id' => 1,
            ],
            [
                'user_id' => 4,
                'nama_toko' => 'Fashionista Store',
                'deskripsi' => 'Pakaian dan aksesoris fashion terbaru.',
                'no_telp' => '082134567891',
                'alamat_toko_id' => 2,
            ],
            [
                'user_id' => 5,
                'nama_toko' => 'Dapur Sehat',
                'deskripsi' => 'Peralatan dapur modern untuk kebutuhan Anda.',
                'no_telp' => '083134567892',
                'alamat_toko_id' => 3,
            ],
            [
                'user_id' => 6,
                'nama_toko' => 'Hobi & Olahraga',
                'deskripsi' => 'Mainan, alat olahraga, dan perlengkapan hobi.',
                'no_telp' => '084134567893',
                'alamat_toko_id' => 4,
            ],
            [
                'user_id' => 7,
                'nama_toko' => 'Kecantikan & Kesehatan',
                'deskripsi' => 'Produk kecantikan dan kesehatan terbaik.',
                'no_telp' => '085134567894',
                'alamat_toko_id' => 5,
            ],
        ]);

        // Alamat Pengguna
        DB::table('alamat_users')->insert([
            [
                'user_id' => 1,
                'nama_penerima' => 'Admin Utama',
                'kode_domestik' => '8427',
                'label' => 'DAGO, PARUNG PANJANG, BOGOR, JAWA BARAT, 16360',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BOGOR',
                'district_name' => 'PARUNG PANJANG',
                'subdistrict_name' => 'DAGO',
                'zip_code' => '16360',
                'detail_alamat' => 'Jl. Raya Dago No. 12, dekat Pasar Parung Panjang',
            ],
            [
                'user_id' => 2,
                'nama_penerima' => 'Admin Kedua',
                'kode_domestik' => '8427',
                'label' => 'DAGO, PARUNG PANJANG, BOGOR, JAWA BARAT, 16360',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BOGOR',
                'district_name' => 'PARUNG PANJANG',
                'subdistrict_name' => 'DAGO',
                'zip_code' => '16360',
                'detail_alamat' => 'Perumahan Griya Asri Blok B2 No. 7',
            ],
            [
                'user_id' => 8,
                'nama_penerima' => 'Andi Susanto',
                'kode_domestik' => '4866',
                'label' => 'BATUNUNGGAL, BANDUNG KIDUL, BANDUNG, JAWA BARAT, 40266',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BANDUNG',
                'district_name' => 'BANDUNG KIDUL',
                'subdistrict_name' => 'BATUNUNGGAL',
                'zip_code' => '40266',
                'detail_alamat' => 'Jl. Batununggal Indah I No. 23 RT 04 RW 05',
            ],
            [
                'user_id' => 9,
                'nama_penerima' => 'Siti Aminah',
                'kode_domestik' => '4844',
                'label' => 'CAMPAKA, ANDIR, BANDUNG, JAWA BARAT, 40184',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'BANDUNG',
                'district_name' => 'ANDIR',
                'subdistrict_name' => 'CAMPAKA',
                'zip_code' => '40184',
                'detail_alamat' => 'Komplek Permata Andir No. 45',
            ],
            [
                'user_id' => 10,
                'nama_penerima' => 'Budi Hartono',
                'kode_domestik' => '5256',
                'label' => 'CIMAHI, CIMAHI TENGAH, CIMAHI, JAWA BARAT, 40525',
                'province_name' => 'JAWA BARAT',
                'city_name' => 'CIMAHI',
                'district_name' => 'CIMAHI TENGAH',
                'subdistrict_name' => 'CIMAHI',
                'zip_code' => '40525',
                'detail_alamat' => 'Jl. Sangkuriang Tengah No. 89, dekat Masjid Al-Hikmah',
            ],
        ]);
    }
}
